### PR TITLE
201 uneven bin widths

### PR DESCRIPTION
**Pull request by rebeccafair**
Addresses #201.

Main points:
* I have added a `method={None, 'convolve}` kwarg to `Spectrum1D/1DCollection/2D.broaden`. If there are unequal bins and `method=None` it will raise a `ValueError`, and if `method='convolve'` it will warn but continue. Default is `method=None`
* I have assumed that the x and y directions are independent i.e. if there are unequal bins in the x-direction, you can still broaden along the y-direction and it wont throw an error or warn. I think this is correct?
* I have set the broadening method for `euphonic-intensity-map` for CL tools to be 'convolve'. I didn't think there was much point in putting a `--broadening-method` in the CL tools for now since we don't actually have any alternatives... this will still warn the user though. I didn't set it for `euphonic-dos` or `euphonic-powder-map` as I think they will always have equal bins with our  current implementation, and at least this will alert us if that changes.

### CODE REVIEW

**Comment by ajjackson** [comment]
> - I have added a method={None, 'convolve} kwarg to Spectrum1D/1DCollection/2D.broaden. If there are unequal bins and method=None it will raise a ValueError, and if method='convolve' it will warn but continue. Default is method=None

This is API breakage, if code following the current rules would raise an error. There should be a deprecation / transition period before the next major version bump.

> - I have assumed that the x and y directions are independent i.e. if there are unequal bins in the x-direction, you can still broaden along the y-direction and it wont throw an error or warn. I think this is correct?

As long it's 1-D broadening, yes. It may fall apart if we bring in broadening with 2-D covariance matrices, but at this stage we don't know how that would look.

> - I have set the broadening method for euphonic-intensity-map for CL tools to be 'convolve'. I didn't think there was much point in putting a --broadening-method in the CL tools for now since we don't actually have any alternatives... this will still warn the user though. I didn't set it for euphonic-dos or euphonic-powder-map as I think they will always have equal bins with our current implementation, and at least this will alert us if that changes.

Sounds good

**Comment by rebeccafair** [comment]
> > * I have added a method={None, 'convolve} kwarg to Spectrum1D/1DCollection/2D.broaden. If there are unequal bins and method=None it will raise a ValueError, and if method='convolve' it will warn but continue. Default is method=None
> 
> This is API breakage, if code following the current rules would raise an error. There should be a deprecation / transition period before the next major version bump.

Good point, now fixed.

**Review by ajjackson — APPROVED** [review]
From the changeset it looks like some quartz Debye-Waller reference data is being deleted. Is that related to these changes, or some incidental cleanup?

Otherwise this looks good to me and behaves as expected.

**Comment by rebeccafair** [comment]
> From the changeset it looks like some quartz Debye-Waller reference data is being deleted. Is that related to these changes, or some incidental cleanup?

Yeah, incidental cleanup. I wasn't convinced that the tests were actually using all the spectrum files so I ran [`pytest-filecov`](https://pypi.org/project/pytest-filecov/0.1.2/), and to my surprise it revealed those files, which have been there a surprisingly long time. Scrictly removing them should be a separate branch but I didn't think it was worth the effort!

**Pull request merged**
