### PR TITLE
90 refactor util

### PR DESCRIPTION
**Pull request by rebeccafair**
Addresses #90

Refactoring to reduce the size of util.py by moving functions with a similar purpose into separate modules, and putting functions into the relevant classes where possible. Commits detail specific changes, hopefully they all make sense.

This has made some changes to how some of the utility functions associated with labelling/plotting (`get_qpoint_labels`, `calc_abscissa`) are called to remove the dependence on `Crystal`, but hopefully it won't affect the plotting refactoring too much.

### CODE REVIEW

**Comment by ajjackson** [comment]
This looks cleaner, easier to navigate and a touch more robust.

My only question is regarding the significance of the leading underscores on the functions accessed from validate. If we're routinely accessing them from other modules, shouldn't they be public?

**Review by ajjackson — APPROVED** [review]
As commented, this is good stuff and I don't see any harm done.

Would query use of leading underscores in the validate functions, but this is not a condition of approval.

**Comment by ajjackson** [comment]
There is a bit of complexity introduced by adopting the spglib cell format alongside our own Crystal class. It's good for interoperability, though. Might also help with import loops, although that isn't the _best_ reason to add redundancy to a code...

**Comment by rebeccafair** [comment]
> This looks cleaner, easier to navigate and a touch more robust.
> 
> My only question is regarding the significance of the leading underscores on the functions accessed from validate. If we're routinely accessing them from other modules, shouldn't they be public?

Yes, I've been wondering what to do about the leading underscores, because although other Euphonic classes/modules use them, I don't really intend for them to be used standalone and I wouldn't want external users or libraries to use them as I'd have to write standalone tests for them and it would take more effort to change their implementation later, I can't seem to find a good consensus on this anywhere....

I guess one solution could be to have all Euphonic object subclass a class which contains the validate functions, but maybe that's over-engineering

**Comment by ajjackson** [comment]
> Yes, I've been wondering what to do about the leading underscores, because although other Euphonic classes/modules use them, I don't really intend for them to be used standalone and I wouldn't want external users or libraries to use them as I'd have to write standalone tests for them and it would take more effort to change their implementation later, I can't seem to find a good consensus on this anywhere....

If the intended meaning is "seriously, use with care" then I'm ok with that. Perhaps that should be documented somehow?

**Comment by rebeccafair** [comment]
> Perhaps that should be documented somehow?

I guess I could put something in the docstring to the gist of `Warning: Intended for internal use only, may change at any time`, but maybe that's redundant as the underscore should imply that anyway. There are a few 'internal' Euphonic functions like this so we should probably come up with a convention and stick with it

**Pull request merged**
